sources:

  # ==========================================================
  # ЛОКАЛЬНЫЕ ФАЙЛЫ
  #
  # Все M3U/M3U8/TXT внутри каталога sources/
  # программа обнаруживает автоматически.
  # ==========================================================

  # Пример отдельного локального источника:
  #
  # - name: "my_local_source"
  #   type: "local"
  #   path: "sources/my_playlist.m3u"
  #   priority: 50
  #   enabled: true


  # ==========================================================
  # БУДУЩИЕ УДАЛЁННЫЕ ПЛЕЙЛИСТЫ
  # ==========================================================

  # Раскомментируй и вставь URL:
  #
  # - name: "remote_source_1"
  #   type: "remote"
  #   url: "http://78.153.139.136:8090/playlists/mirovoy_iptv.m3u"
  #   priority: 100
  #   enabled: true

  # - name: "remote_source_2"
  #   type: "remote"
  #   url: "https://loganettv.github.io/playlists/all.m3u"
  #   priority: 80
  #   enabled: true
  
  # - name: "remote_source_1"
  #   type: "remote"
  #   url: "https://homtv.ru/8124907.m3u"
  #   priority: 100
  #   enabled: true